name: Practice 2 - Event Name Detector

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  echo:
    name: Event Detector
    runs-on: ubuntu-latest
    steps:
      - name: Show triggering event
        run: echo "I've been triggered by ${{ github.event_name }} event"
