name: Practice 3 - Event Filters

on:
  push:
    branches:
      - dev
      - 'release/*'
    paths-ignore:
      - 'docs/**'

jobs:
  test-filters:
    name: Test Filters
    runs-on: ubuntu-latest
    steps:
      - name: Show success message
        run: echo "Event filters working! Triggered on ${{ github.ref_name }} branch by ${{ github.event_name }} event"
